### ISSUE TITLE
Missing 4 frames encoders and decoders

### ISSUE THREAD

**Issue by RandallFlagg** [jcoutch/id3-DotNetCore#3]
CopyrightFrame
FileTypeFrame
LengthFrame
LyricistsFrame

**Comment by jcoutch** [comment]
Thanks for the pull request!  After reviewing it, everything looks good, and these changes have been deployed to Nuget in version 0.4.0.13:
https://www.nuget.org/packages/ID3.Files-DotNetCore/0.4.0.13
